[supervisord]
nodaemon=true

[program:node]
command=xvfb-run --auto-servernum /usr/bin/node /app/dist/index.js
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0