[supervisord]
nodaemon=true

[program:kozun]
command=xvfb-run --auto-servernum /usr/bin/wine /app/RCCService/kozun.exe
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:node]
command=/usr/bin/node /app/dist/Main.js
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0