<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DSharpPlus" Version="4.5.2" />
    <PackageReference Include="JWT" Version="11.1.0" />
    <PackageReference Include="NetVips" Version="3.2.0" />
    <PackageReference Include="NetVips.Native.linux-x64" Version="8.18.4" />
    <PackageReference Include="NetVips.Native.win-x64" Version="8.18.4" />
    <PackageReference Include="Sodium.Core" Version="1.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Roblox.Logging\Roblox.Logging.csproj" />
    <ProjectReference Include="..\Roblox.Models\Roblox.Models.csproj" />
  </ItemGroup>

</Project>
