<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Roblox.ServiceDefaults\Roblox.ServiceDefaults.csproj" />
        <ProjectReference Include="..\..\Roblox.Dto\Roblox.Dto.csproj" />
        <ProjectReference Include="..\..\Roblox.Services\Roblox.Services.csproj" />
        <ProjectReference Include="..\..\Roblox.Web.Infrastructure\Roblox.Web.Infrastructure.csproj" />
    </ItemGroup>

</Project>
