<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>8618</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Fleck" Version="1.2.0" />
    <PackageReference Include="JWT" Version="11.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.3" />
    <PackageReference Include="TwoFactorAuth.Net" Version="1.4.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Public" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Keys\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Update="download.html;oauth.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Roblox.AbuseDetection\Roblox.AbuseDetection.csproj" />
    <ProjectReference Include="..\Roblox.Configuration\Roblox.Configuration.csproj" />
    <ProjectReference Include="..\Roblox.Dto\Roblox.Dto.csproj" />
    <ProjectReference Include="..\Roblox.EconomyChat\Roblox.EconomyChat.csproj" />
    <ProjectReference Include="..\Roblox.Libraries\Roblox.Libraries.csproj" />
    <ProjectReference Include="..\Roblox.Models\Roblox.Models.csproj" />
    <ProjectReference Include="..\Roblox.Services\Roblox.Services.csproj" />
    <ProjectReference Include="..\Services\Roblox.ServiceDefaults\Roblox.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Roblox.Web.Infrastructure\Roblox.Web.Infrastructure.csproj" />
    <ProjectReference Include="..\Roblox.Exceptions\Roblox.Exceptions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <_ContentIncludedByDefault Remove="Pages\Admi\Home.cshtml" />
  </ItemGroup>
</Project>
